### ISSUE TITLE
Antwoord bug

### ISSUE THREAD

**Issue by muhammet075** [lisannevvliet/live-trivia#15]
Als ik op een antwoord klik, en niemand heeft nog op wat geklikt dan wacht ik, pas als mensen een antwoord hebben gekozen wordt de volgende vraag ingeladen en dan kan ik niet zien of mijn keuze goed of fout was van de vorige vraag.

**Comment by lisannevvliet** [comment]
Expanded the delay from half a second to a second, so that the user has more time to view whether their answer was correct.
